package com.roshka.sifen.core.types;

import java.util.Arrays;

public enum CMondT {
    AED("Dirham"),
    AFN("Afghani"),
    ALL("Lek"),
    AMD("Dram"),
    ANG("Netherlands Antillian Guilder"),
    AOA("Kwanza"),
    ARS("Argentine Peso"),
    AUD("Australian Dollar"),
    AWG("Aruban Guilder"),
    AZM("Azerbaijanian Manat"),
    BAM("Convertible Mark"),
    BBD("Barbados Dollar"),
    BYN("Belarusian Ruble"),
    BDT("Taka"),
    BGN("Bulgarian Lev"),
    BHD("Bahraini Dinar"),
    BIF("Burundi Franc"),
    BMD("Bermudian Dollar (customarily: Bermuda Dollar)"),
    BND("Brunei Dollar"),
    BOB("Boliviano"),
    BOV("Mvdol"),
    BRL("Brazilian Real"),
    BSD("Bahamian Dollar"),
    BTN("Ngultrum"),
    BWP("Pula"),
    BYR("Belarussian Ruble"),
    BZD("Belize Dollar"),
    CAD("Canadian Dollar"),
    CDF("Franc Congolais"),
    CHF("Swiss Franc"),
    CHE("WIR Euro"),
    CHW("WIR Franc"),
    CLP("Chilean Peso"),
    CLF("Unidad de Fomento"),
    CNY("Yuan Renminbi"),
    COP("Colombian Peso"),
    COU("Unidad de Valor Real"),
    CRC("Costa Rican Colon"),
    CUP("Cuban Peso"),
    CUC("Peso Convertible"),
    CVE("Cape Verde Escudo"),
    CYP("Cyprus Pound"),
    CZK("Czech Koruna"),
    DJF("Djibouti Franc"),
    DKK("Danish Krone"),
    DOP("Dominican Peso"),
    DZD("Algerian Dinar"),
    EEK("Kroon"),
    EGP("Egyptian Pound"),
    ERN("Nakfa"),
    ETB("Ethopian Birr"),
    EUR("Euro"),
    FJD("Fiji Dollar"),
    FKP("Falkland Islands Pound"),
    GBP("Pound Sterling"),
    GEL("Lari"),
    GHS("Ghana Cedi"),
    GHC("Cedi"),
    GIP("Gibraltar Pound"),
    GMD("Dalasi"),
    GNF("Guinea Franc"),
    GTQ("Quetzal"),
    GYD("Guyana Dollar"),
    HKD("Honk Kong Dollar"),
    HNL("Lempira"),
    HRK("Kuna"),
    HTG("Gourde"),
    HUF("Forint"),
    IDR("Rupiah"),
    ILS("New Israeli Sheqel"),
    INR("Indian Rupee"),
    IQD("Iraqi Dinar"),
    IRR("Iranian Rial"),
    ISK("Iceland Krona"),
    JMD("Jamaican Dollar"),
    JOD("Jordanian Dinar"),
    JPY("Yen"),
    KES("Kenyan Shilling"),
    KGS("Som"),
    KHR("Riel"),
    KMF("Comoro Franc"),
    KPW("North Korean Won"),
    KRW("Won"),
    KWD("Kuwaiti Dinar"),
    KYD("Cayman Islands Dollar"),
    KZT("Tenge"),
    LAK("Kip"),
    LBP("Lebanese Pound"),
    LKR("Sri Lanka Rupee"),
    LRD("Liberian Dollar"),
    LSL("Loti"),
    LTL("Lithuanian Litas"),
    LVL("Latvian Lats"),
    LYD("Libyan Dinar"),
    MAD("Morrocan Dirham"),
    MZN("Mozambique Metical"),
    MDL("Moldovan Leu"),
    MGF("Malagasy Franc"),
    MKD("Denar"),
    MGA("Malagasy Ariary"),
    MMK("Kyat"),
    MNT("Tugrik"),
    MOP("Pataca"),
    MRO("Ouguiya"),
    MTL("Maltese Lira"),
    MUR("Mauritius Rupee"),
    XUA("ADB Unit of Account"),
    MVR("Rufiyaa"),
    MRU("Ouguiya"),
    MWK("Kwacha"),
    MXN("Mexican Peso"),
    MXV("Mexican Unidad de Inversion"),
    MYR("Malaysian Ringgit"),
    MZM("Metical"),
    NAD("Namibia Dollar"),
    NGN("Naira"),
    NIO("Cordoba Oro"),
    NOK("Norwegian Krone"),
    NPR("Nepalese Rupee"),
    NZD("New Zealand Dollar"),
    OMR("Rial Omani"),
    PAB("Balboa"),
    PEN("Nuevo Sol"),
    PGK("Kina"),
    PHP("Philippine Peso"),
    PKR("Pakistan Rupee"),
    PLN("Zloty"),
    PYG("Guarani"),
    QAR("Qatari Rial"),
    RON("Romanian Leu"),
    ROL("Leu"),
    RUB("Russian Ruble"),
    RWF("Rwanda Franc"),
    SAR("Saudi Riyal"),
    RSD("Serbian Dinar"),
    SBD("Solomon Islands Dollar"),
    SCR("Seychelles Rupee"),
    SDD("Sudanese Dinar"),
    SDG("Sudanese Pound"),
    SRD("Surinam Dollar"),
    SEK("Swedish Krona"),
    SGD("Singapore Dollar"),
    SHP("St. Helena Pound"),
    SIT("Tolar"),
    SKK("Slovak Koruna"),
    SLL("Leone"),
    SOS("Somali Shilling"),
    SRG("Suriname Guilder"),
    SSP("South Sudanese Pound"),
    STD("Dobra"),
    SVC("El Salvador Colon"),
    SYP("Syrian Pound"),
    SZL("Lilangeni"),
    THB("Baht"),
    TJS("Somoni"),
    TMM("Manat"),
    TND("Tunisian Dinar"),
    TRY("Turkish Lira"),
    TMT("Turkmenistan New Manat"),
    TOP("Pa&apos;anga"),
    TRL("Turkish Lira"),
    TTD("Trinidad and Tobago Dollar"),
    TWD("New Taiwan Dollar"),
    TZS("Tanzanian Shilling"),
    UAH("Hryvnia"),
    UGX("Uganda Shilling"),
    USD("US Dollar"),
    USN("US Dollar(Next day)"),
    UYU("Peso Uruguayo"),
    UYI("Uruguay Peso en Unidades Indexadas(UI)"),
    UYW("Unidad Previsional"),
    UZS("Uzbekistan Sum"),
    VEB("Bolivar"),
    VND("Dong"),
    VUV("Vatu"),
    VES("Bolivar Soberano"),
    WST("Tala"),
    STN("Dobra"),
    XAF("CFA Franc"),
    XAG("Silver"),
    XAU("Gold"),
    XCD("East Carribean Dollar"),
    XDR("SDR"),
    XOF("CFA Franc"),
    XPD("Palladium"),
    XPF("CFP Franc"),
    XPT("Platinum"),
    XSU("Sucre"),
    XBA("Bond Markets Unit European Composite Unit(EURCO)"),
    XBB("Bond Markets Unit European Monetary Unit(E.M.U.-6)"),
    XBC("Bond Markets Unit European Unit of Account 17 (E.U.A.-17)"),
    XTS("Codes specifically reserved for testing purposes"),
    XXX("The codes assigned for transactions where no currency is involved"),
    YER("Yemeni Rial"),
    YUM("New Dinar"),
    ZMW("Zambian Kwacha"),
    ZWL("Zimbabwe Dollar"),
    ZAR("Rand"),
    ZMK("Kwacha"),
    ZWD("Zimbabwe Dollar");

    private String descripcion;

    CMondT(String descripcion) {
        this.descripcion = descripcion;
    }

    public static CMondT getByName(String name) {
        return Arrays.stream(CMondT.values()).filter(e -> e.name().equalsIgnoreCase(name)).findFirst().orElse(null);
    }

    public String getDescripcion() {
        return descripcion;
    }

    @Override
    public String toString() {
        return "{\"descripcion\":\"" + descripcion + "\"}";
    }
}